Ice<-ts(Area_of_Sea_Ice[,c(2,4,6,7)],start=1990, end=2017+2/12, frequency = 12)
tail(Ice)
training<-ts(Ice[1:264,],start=1990,end=2011+11/12,frequency = 12)
validation<-ts(Ice[265:288,],start=2012,end=2013+11/12,frequency = 12)
par(mar=c(3,5,2,2))
plot(training[,1],ylab=expression(paste("Sea Ice Extent (millions ", km^2,")")),main="Arctic Sea Ice extent times series")
plot(training[,2],ylab=expression(paste("Sea Ice Extent (millions ", km^2,")")),main="Antarctic Sea Ice extent times series")
tsdisplay(training[,1])
######STL
stl1<-stl(training[,1],"periodic")
stl2<-stl(training[,2],"periodic")
plot(stl(training[,1],"periodic"),main="Arctic Sea Ice Extent Decomposition")
plot(stl(training[,2],"periodic"),main="Antrctic Sea Ice Extent Decomposition")
plot(training[,1], col="gray",ylab=expression(paste("Sea Ice Extent (millions ", km^2,")")),main="Arctic Sea Ice extent times series")
plot(training[,2], col="gray",ylab=expression(paste("Sea Ice Extent (millions ", km^2,")")),main="Antarctic Sea Ice extent times series")
lines(fit2$time.series[,2],col="red",ylab="Trend")
legend("bottomleft","trend",lty=1,col="red")
sarima(stl1$time.series[,"remainder"],0,0,0)
faststln <- forecast(stl1, method="arima",h=24)
plot(fcast, ylab=expression(paste("Sea Ice Extent (millions ", km^2,")")))
faststls <- forecast(stl2, method="arima",h=24)
plot(fcast1, ylab=expression(paste("Sea Ice Extent (millions ", km^2,")")))
write.csv(faststln, "stln.csv")
write.csv(faststls, "stls.csv")
##########ETS
etsn<-ets(training[,1])
etss<-ets(training[,2])
etsn
etss
plot(etsn)
plot(etss)
lss<-ls[,2]
lss<-ts(lss,start=1990,end=2011+11/12,frequency = 12)
fitls<-lm(lss~time(lss))
plot(lss,ylab=expression(paste("Sea Ice Extent (millions ", km^2,")")),main='ETS level with fitted line for Antarctic')
abline(fitls,col='red',lty=2)
legend("bottomleft","slope=-0.066",lty=2,col='red')
legend("bottomleft","slope=0.015",lty=2,col='red')
fasten<-forecast(etsn,h=24)
plot(fasten,ylab=expression(paste("Sea Ice Extent (millions ", km^2,")")))
fastes<-forecast(etss,h=24)
plot(fastes,ylab=expression(paste("Sea Ice Extent (millions ", km^2,")")))
write.csv(fasten, "etsn.csv")
write.csv(fastes, "etss.csv")
#################ARIMA
arin<-auto.arima(training[,1])
aris<-auto.arima(training[,2])
arin
sarima(arin$residuals,0,0,0)
plot(training[,1],type="p",col='red',ylab=expression(paste("Sea Ice Extent (millions ", km^2,")")),main="data against fitted")
lines(training[,1]-arin$residuals,lty=2)
legend("bottomleft",c("data","fitted"),pch=c(1,NA),lty=c(NA,2),col=c(2,1))
fastarin<-forecast(arin,h=24)
plot(fastarin,ylab=expression(paste("Sea Ice Extent (millions ", km^2,")")))
aris
sarima(aris$residuals,0,0,0)
plot(training[,2],type="p",col='red',ylab=expression(paste("Sea Ice Extent (millions ", km^2,")")),main="data against fitted")
lines(training[,2]-aris$residuals,lty=2)
legend("bottomleft",c("data","fitted"),pch=c(1,NA),lty=c(NA,2),col=c(2,1))
fastaris<-forecast(aris,h=24)
plot(fastaris,ylab=expression(paste("Sea Ice Extent (millions ", km^2,")")))
write.csv(fastarin, "arin.csv")
write.csv(fastaris, "aris.csv")
####write.csv(fcast1, "stls.csv")
############VAR
N<-training[,1:3]
S<-training[,c(2,1,4)]
VARselect(N)
VN<-VAR(N,p=9,type="both")
var_residuals<-resid(VN)[,1]
acf2(var_residuals)
summary(VN)
fastvn<-forecast(VN,h=24)
fastvs$mean$Exten
plot(fastvn)
plot(fastvn$mean$Extent)
VARselect(S)
VS<-VAR(S,p=10,type="both")
var_residuals<-resid(VS)[,1]
acf2(var_residuals)
summary(VS)
fastvs<-forecast(VS,h=24)
plot(fastvs)
write.csv(fastvn$mean$Extent, "varn.csv")
write.csv(fastvs$mean$Extent.ant., "vars.csv")
